function result = structToArgInfo(s)
%STRUCTTOARGINFO Convert a MEX struct to a soapysdr.ArgInfo object.
%   result = structToArgInfo(s) converts a scalar struct with fields
%   Key, Value, Name, Description, Units, Type, Range, Options,
%   OptionNames to a soapysdr.ArgInfo.

    rangeStruct = s.Range;
    rangeObj = soapysdr.Range( ...
        rangeStruct.Minimum, rangeStruct.Maximum, rangeStruct.Step);

    result = soapysdr.ArgInfo( ...
        Key=string(s.Key), ...
        Value=string(s.Value), ...
        Name=string(s.Name), ...
        Description=string(s.Description), ...
        Units=string(s.Units), ...
        Type=string(s.Type), ...
        Range=rangeObj, ...
        Options=string(s.Options), ...
        OptionNames=string(s.OptionNames));
end
